corrected path to script

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,10 @@
 #!/bin/sh
 
-echo "AnyScript"
-exit 0
+# this pack is valid for apps with a hello.txt in the root
+if [ -f $1/heroku-buildpack-anyscript.sh ]; then
+  echo "heroku-buildpack-anyscript script found"
+  exit 0
+else
+  echo "heroku-buildpack-anyscript script NOT found"
+  exit 1
+fi
